{% set name = "qbatch" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qbatch-{{ version }}.tar.gz
  sha256: 84dcd5f0650c694f0796aeb53e36b60e2388795f80d8c8a919b2379ead2a0193

build:
  entry_points:
    - qbatch=qbatch:qbatchParser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future

test:
  imports:
    - qbatch
  commands:
    - pip check
    - qbatch --help
  requires:
    - pip

about:
  home: https://github.com/pipitone/qbatch
  summary: Execute shell command lines in parallel on Slurm, S(un|on of) Grid Engine (SGE) and PBS/Torque clusters
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
